### ISSUE TITLE
Access denied to the pre-built dataset

### ISSUE THREAD

**Issue by Meenal002** [nch-igm/rna-stability#1]
Hi,
I was trying to load the Prebuilt Apache Parquet dataset into local Spark environment using the following command:
<pre><code>aws s3 ls s3://nch-igm-rna-stability/RNAStability_v10.2_2019_03_06_3_ALL_gnomAD_Final.parquet</code></pre>

This is the error I get:
<pre><code>An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied </code></pre>

I was also unable to access the s3 bucket via http. 

Thanks in advance for your help

**Comment by mikecormier** [comment]
I am also having a problem accessing the data stored in your S3 bucket. Could you update the permissions for the `nch-igm-rna-stability` s3 bucket so we can access the parquet files loaded there?

**Comment by gel001** [comment]
Terribly sorry about the troubles. It appears that there was access misconfiguration on the bucket which has now been fixed. I've tested the new settings from a completely different AWS account on a non-IGM server and it appears to work now.
